### ISSUE TITLE
Boss Stones

### ISSUE THREAD

**Issue by J0HNN1E** [OrianaVenture/VentureValheim#12]
Hello,

There is a little bug on the bosses stones : 
- When people are trying to put boss trophies on it, they should click alot of time to achieve it.
- People which didn't killed boss (for example Eikthyr) could take the power on the boss stone, is that normal?

I thought this mod was preventing this second thing.

Best regards and thanks alot for your mod!
JOHNN1E

**Comment by OrianaVenture** [comment]
That is expected behavior right now. I plan on adding the ability to block getting the boss powers if you have not defeated a boss in the future.

**Comment by OrianaVenture** [comment]
This is now in version 0.0.21 moving forward.
