### ISSUE TITLE
Logout Tweak after i dies with status effect

### ISSUE THREAD

**Issue by hisoscream** [OrianaVenture/VentureValheim#13]
![image](https://user-images.githubusercontent.com/15785960/219932255-b8e1a3b8-da9b-4e0e-a71e-17030fda0a04.png)

**Comment by hisoscream** [comment]
it will blackscreen. i can still close app and re open

**Comment by OrianaVenture** [comment]
Is this problem still happening? Logout Tweaks does not edit the Status Effect manager, so my initial thought is that this might be another mod. Status Effects from your last logout are applied when the character is loaded only. It's possible that an old status effect was added to your player that might be causing an issue. If you are playing with any other mod that adds/edits status effects can you please list them?
