### ISSUE TITLE
Progression Incompatability with Epic Loot

### ISSUE THREAD

**Issue by Mofker** [OrianaVenture/VentureValheim#14]
While using Progression with Private Keys enabled and running Epic Loot, upon trying to log off I get stuck in a black screen with the following error in console,

 [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ZNetView.InvokeRPC (System.String method, System.Object[] parameters) (at <0a1a436be26b421bb46752e573a7aa2f>:0)
VentureValheim.Progression.KeyManager.SendPrivateKey (Player player, System.String key) (at <287518290501407490164a3261759c78>:0)
VentureValheim.Progression.KeyManager+Patch_ZoneSystem_SetGlobalKey.Postfix (System.String name) (at <287518290501407490164a3261759c78>:0)
(wrapper dynamic-method) ZoneSystem.DMD<ZoneSystem::SetGlobalKey>(ZoneSystem,string)
EpicLoot.Adventure.Feature.BountiesAdventureFeature.SaveBountyLedger () (at <3445a66d20694f088e28b9e0c6e99344>:0)
EpicLoot.Adventure.Feature.BountiesAdventureFeature.OnWorldSave () (at <3445a66d20694f088e28b9e0c6e99344>:0)
EpicLoot.Adventure.AdventureDataManager.OnWorldSave () (at <3445a66d20694f088e28b9e0c6e99344>:0)
EpicLoot.ZNet_SaveWorld_Patch.Prefix (ZNet __instance) (at <3445a66d20694f088e28b9e0c6e99344>:0)
(wrapper dynamic-method) ZNet.DMD<ZNet::SaveWorld>(ZNet,bool)
ZNet.Save (System.Boolean sync) (at <0a1a436be26b421bb46752e573a7aa2f>:0)
(wrapper dynamic-method) ZNet.DMD<ZNet::Shutdown>(ZNet)
(wrapper dynamic-method) Game.DMD<Game::Shutdown>(Game)
(wrapper dynamic-method) Game.DMD<Game::Logout>(Game)
Menu.Logout () (at <0a1a436be26b421bb46752e573a7aa2f>:0)
Menu.OnLogoutYes () (at <0a1a436be26b421bb46752e573a7aa2f>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <c9fb31c2eee14ce4aeb36e4c61e154d8>:0)
UnityEngine.UI.Button.Press () (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <67859b8eac9e4f3b99606821e32b26c6>:0)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by OrianaVenture** [comment]
I actually changed some of the code around this so you will never see this specific error again after updating to version 0.24. If there are new problems that come up while using the Epic Loot Bounties system please share the new errors and I will see if I can fix it if there ends up being an issue.
