### ISSUE TITLE
PlayerDefaultSpawnPoint has no effect

### ISSUE THREAD

**Issue by jpee85** [OrianaVenture/VentureValheim#16]
Hey, 
I do not get the default spawn point to work.

I tried

PlayerDefaultSpawnPoint = 383.0,29.0
PlayerDefaultSpawnPoint = 0,0
PlayerDefaultSpawnPoint = -9927.0,310.0
PlayerDefaultSpawnPoint = -9927,310

it seems new characters always spawn inside the stone circle.

Other features of the mod are working fine, like disabling Valkrie.

Issue detected with 0.4.6 on previous stable Valheim.

Base config:

[Arrival]

## Coordinates for the default player spawn point (x,z) no parentheses, leave empty to use game default (comma-separated floats). [Synced with Server]
# Setting type: String
# Default value: 
PlayerDefaultSpawnPoint = 383.0,29.0

## True to enable Valkrie Intro (boolean). [Synced with Server]
# Setting type: Boolean
# Default value: true
EnableValkrie = false

## True to enable Arrival Message on player login (boolean). [Synced with Server]
# Setting type: Boolean
# Default value: true
EnableArrivalMessage = true

## False to use a Normal message when EnableArrivalMessage is True (boolean). [Synced with Server]
# Setting type: Boolean
# Default value: true
UseArrivalShout = true

## Set a new arrival message, leave blank to use default (string). [Synced with Server]
# Setting type: String
# Default value: 
OverrideArrivalMessage = 

[General]

## Force Server Config (boolean). [Synced with Server]
# Setting type: Boolean
# Default value: true
Force Server Config = true

## Enable module (boolean). [Synced with Server]
# Setting type: Boolean
# Default value: true
Enabled = true

## Maximum Players for the Server (integer). [Synced with Server]
# Setting type: Int32
# Default value: 10
MaximumPlayers = 10

## Override Player pvp behavior (boolean). [Synced with Server]
# Setting type: Boolean
# Default value: false
OverridePlayerPVP = false

## True to set pvp always on when OverridePlayerPVP is True (boolean). [Synced with Server]
# Setting type: Boolean
# Default value: true
ForcePlayerPVPOn = true

## False to respawn players at their graves on a PVP death (boolean). [Synced with Server]
# Setting type: Boolean
# Default value: true
TeleportOnPVPDeath = true

## False to prevent skill loss on a PVP death (boolean). [Synced with Server]
# Setting type: Boolean
# Default value: true
SkillLossOnPVPDeath = true

[Map]

## True to allow Haldor map pin on Minimap (boolean). [Synced with Server]
# Setting type: Boolean
# Default value: true
EnableHaldorMapPin = true

## Override Player map pin position behavior for Minimap (boolean). [Synced with Server]
# Setting type: Boolean
# Default value: false
OverridePlayerMapPositions = false

## True to always show Player position on Minimap when OverridePlayerMapPositions is True (boolean). [Synced with Server]
# Setting type: Boolean
# Default value: true
ForcePlayerMapPositionOn = true

**Comment by OrianaVenture** [comment]
Sorry it took so long to get back to you. Do you know if the spawn point is working after the player tries to respawn for a second time? Or is it only an issue for the player's first spawn? I will do some testing with the new game version to see if I can replicate the issue.

**Comment by OrianaVenture** [comment]
Seems like the game can't determine the ground height of the spawn location every time. If the zone is already loaded it seems to work, but trying to spawn at a default location further away from the death point does not. I may just add in an option to specify the height of the default spawn location which will prevent this issue from happening if I there's no way to fix it otherwise.

**Comment by OrianaVenture** [comment]
This should be fixed in version 0.4.8, I added a y field to the config to prevent the issue from happening.

**Comment by jpee85** [comment]
Works like a charm. Thank you Oriana!
