### ISSUE TITLE
RESET CAMPS

### ISSUE THREAD

**Issue by ErDuh** [OrianaVenture/VentureValheim#17]
Hello Oriana,

When a player moves away from a fuling camp and returns, he regenerates. It doesn't happen all the time but it does. 
If I use killall it doesn't happen, only when a player attacks directly.

If you want, you can log into our HIJOS DE FREYJA server and try it with admin mode.
https://discord.gg/hijos-de-freyja-818547021777993748

Thanks

**Comment by OrianaVenture** [comment]
@ErDuh This should be fixed in version 0.3.1, if you still have issues you can reopen this ticket or reach out to me on discord.

**Comment by ErDuh** [comment]
Thank u!
