### ISSUE TITLE
meadow farms

### ISSUE THREAD

**Issue by vitalikbyrevich** [OrianaVenture/VentureValheim#18]
Good afternoon. Houses in the Meadows with hives are restored every time a player leaves the area. In the configuration is 50 days. But as soon as the player runs between two houses - they are restored. That is, the player gets an infinite supply of bees. Maybe there is a conflict with the mod DayCycle? I set the coefficient of 0.33.

**Comment by vitalikbyrevich** [comment]
[com.orianaventure.mod.LocationReset.txt](https://github.com/OrianaVenture/VentureValheim/files/11441705/com.orianaventure.mod.LocationReset.txt)

**Comment by OrianaVenture** [comment]
I think this is the same issue that some people have been seeing with fuling camps. I don't think it's a mod conflict, but DayCycle might be causing the time to be off, I'm not sure. I am looking into the issue and will try to figure out why this is happening.

**Comment by OrianaVenture** [comment]
@vitalikbyrevich This should be fixed in version 0.3.1, if you still have issues you can reopen this ticket or reach out to me on discord.
