### ISSUE TITLE
Sea Of Noodles Configuration Options

### ISSUE THREAD

**Issue by searica** [OrianaVenture/VentureValheim#20]
Hello Oriana,

I was wondering if you would be open to adding user configuration options to Sea of Noodles so users can customize each of the features values. 

Alternatively,  if you're open to it and would prefer it I could add them to the mod and then make a pull request. Probably wouldn't be able to get to that until some time in October though.

Thanks for your mods!

**Comment by OrianaVenture** [comment]
Hi searica,

The mod was intended to be simple and without any configurations. There are other mods that will let you fully edit spawn rates such as this mod https://valheim.thunderstore.io/package/ASharpPen/Spawn_That/. I felt that feature wasn't necessary as I was just making an easier way to boost one particular creature spawn in the game. However, if you feel the spawn rates are still not high enough after playing with the mod (or need to be decreased) I would be willing to tweak the balance.

If you wish to have full customization you will have to use another mod, or you can fork the project and add those features yourself and release a new mod. All I ask is that if you do that you change the name of the mod and remove my name from it.
