### ISSUE TITLE
Compatibility Question

### ISSUE THREAD

**Issue by agmaro** [OrianaVenture/VentureValheim#26]
Hi! I'm running your mod on a dedicated server and it's not working. I assume it's because of this other mod: "https://valheim.thunderstore.io/package/Digitalroot/Max_Dungeon_Rooms/". I get this error:

[Info   : Unity Log] 11/23/2023 11:38:13: Loading dungeon

[Info   : Unity Log] 11/23/2023 11:38:13: Dungeon loaded with 24 rooms in 22,4995 ms.

[Info   :DungeonReset] Loaded dungeon 'DG_SunkenCrypt (1738, 5032, 1728)' with theme SunkenCrypt

[Info   :DungeonReset] Dungeon 'DG_SunkenCrypt (1738, 5032, 1728)' was captured!

[Info   :DungeonReset] Dungeon 'DG_SunkenCrypt (1738, 5032, 1728)' was scheduled for reset in 3 seconds!

[Info   : Unity Log] 11/23/2023 11:38:13: Loading dungeon

[Info   : Unity Log] 11/23/2023 11:38:13: Dungeon loaded with 41 rooms in 33,0799 ms.

[Info   :DungeonReset] Loaded dungeon 'DG_SunkenCrypt (1739, 5032, 1843)' with theme SunkenCrypt

[Info   :DungeonReset] Dungeon 'DG_SunkenCrypt (1739, 5032, 1843)' was captured!

[Info   :DungeonReset] Dungeon 'DG_SunkenCrypt (1739, 5032, 1843)' was scheduled for reset in 4 seconds!

[Error  : Unity Log] MissingMethodException: Method not found: long .ZDOMan.GetMyID()
Stack trace:
DungeonReset.Timer+<Cycle>d__7.MoveNext () (at J:/ValMods/~DungeonReset/Scripts/Timer.cs:41)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <50b18efe22344b9eb3b7d77b08ea287f>:0)

[Error  : Unity Log] MissingMethodException: Method not found: long .ZDOMan.GetMyID()
Stack trace:
DungeonReset.Timer+<Cycle>d__7.MoveNext () (at J:/ValMods/~DungeonReset/Scripts/Timer.cs:41)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <50b18efe22344b9eb3b7d77b08ea287f>:0)

Can you help me? Thanks a lot!

**Comment by OrianaVenture** [comment]
Hi agmaro, DungeonReset is not my mod. That one has not been updated. My mod is Location Reset and will show up in the log file as such.

**Comment by agmaro** [comment]
You're absolutely right! I'm sorry, it was an old .cfg file from that other mod in the dedicated server. I deleted it and now yours is working perfectly. Well, at least now everyone knows that your (btw amazing) mod works with "max dungeon rooms". Thanks a lot, keep up the amazing work!! :D
