### ISSUE TITLE
Progression Gamepass Error

### ISSUE THREAD

**Issue by pncorpuz** [OrianaVenture/VentureValheim#27]
Hi, 

I'm using the xbox gamepass version and I'm getting this error:

[Error  : Unity Log] TypeLoadException: Could not load type ZSteamMatchmaking, assembly_valheim, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null while decoding custom attribute: (null)
Stack trace:
System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inheritedOnly) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
System.RuntimeType.GetCustomAttributes (System.Boolean inherit) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
HarmonyLib.HarmonyMethodExtensions.GetFromType (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor..ctor (HarmonyLib.Harmony instance, System.Type type, System.Boolean allowUnannotatedType) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor..ctor (HarmonyLib.Harmony instance, System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.CreateClassProcessor (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
VentureValheim.Progression.ProgressionPlugin.Awake () (at <bab25184d45843e1849bccc4501c211f>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.UI.Graphic:get_canvas()
TMPro.TextMeshProUGUI:OnCanvasHierarchyChanged()

Although I believe its not affecting any of my gameplays I just thought I would let you know, tag it as enhancement if you like

**Comment by pncorpuz** [comment]
[LogOutput.log](https://github.com/OrianaVenture/VentureValheim/files/13537398/LogOutput.log)

Yes, sorry my bad please see attached.

**Comment by OrianaVenture** [comment]
There is a patch I put in a previous update that was used to fix world save corruption. The patch can't apply itself because the gamepass version does not have the ZSteamMatchmaking file. If it is not causing any issues you can just ignore the error. That code is going to be removed in a future update since I believe it is not needed anymore. Thanks for the report, will leave this open until I can address this.

**Comment by OrianaVenture** [comment]
Removed in version 0.2.11 and added to Venture Debugger version 0.0.3
