### ISSUE TITLE
Asocial Cartography - Add additional configurations for boss pins

### ISSUE THREAD

**Issue by Oosquai** [OrianaVenture/VentureValheim#29]
Hi there!  Thanks for all the great mods you produce!  Would you please consider adding a config option to MultiplayerTweaks to hide the Hildir quest location map icons?  Thank you!

**Comment by OrianaVenture** [comment]
Hi [Oosquai](https://github.com/Oosquai),

What is the use case for this request? The Hildir map icons work like regular map pins you would normally place, you can only get them if you visit Hildir and read her map (or get them from a cartography table). Removing that feature from the game isn't something I would want to add to the mod.

If the issue is other players sharing the map pin on the cartography table that can be a feature potentially added to my Asocial Cartography mod.

**Comment by Oosquai** [comment]
Hi OrianaVenture!  Thanks for the quick reply.  You're probably right that this would be more appropriate to control through your Asocial Cartography mod.  Do you mean players would each have to 1) find Hildir on their own, assuming her pin is turned off with AC, then 2) interact with her map to get her destination pins, none of which would get shared through the cartography table?  If so, sounds cool to me!  Thanks for all your work making Valheim even more awesome!

**Comment by OrianaVenture** [comment]
For the change I would make it would be a client side controlled config that just stops players from adding/taking Hildir map pins to the table, I can also put in support for all the boss pins too easily enough. So in that case the player will have to go to Hildir to get the map pins if nobody else shares them to their table. AC isn't server controlled, so if you wanted to force them off you will need to find someone willing to make that mod for you.

I don't find it aligns with vanilla to completely remove them from the game, unless that is needed for a custom map where you have moved or removed the mini-bosses making the pins inaccurate. In that case it is a bit outside the scope of my work at the moment, but is something I may be willing to do in the future after some more thought.

**Comment by Oosquai** [comment]
Your client-side suggestion sounds fantastic, and I'd be a fan of adding similar configs for bosses as well!  Thank you!

**Comment by OrianaVenture** [comment]
This is now a live feature in version 0.2.0

**Comment by Oosquai** [comment]
Awesome, thank you!!
