### ISSUE TITLE
Old pre hildir patches

### ISSUE THREAD

**Issue by ImpulsiveFPS** [OrianaVenture/VentureValheim#32]
[Debug  :TerminalChecker] Assembly `VentureValheim.Progression` appears to be old and has a Prefix patch on method InitTerminal in Terminal class. Inside the following patch: Prefix

[Debug  :TerminalChecker] Assembly `VentureValheim.Progression` appears to be old and has a Postfix patch on method InitTerminal in Terminal class. Inside the following patch: Postfix

**Comment by OrianaVenture** [comment]
@ImpulsiveFPS Are you seeing any issues in game? That mod can flag mods that are up to date sometimes. I need to know what mod versions you are using and what game version if you are having problems with my mod.
