### ISSUE TITLE
Error while playing after the new update

### ISSUE THREAD

**Issue by Dash200017** [OrianaVenture/VentureValheim#35]
[Uploading LogOutput.log…]()

[Message:GsiX MultiCraft] MultiCraft Button Success
[Info   : Unity Log] 04/12/2024 14:00:42: Minimap: Adding unique location (1.99, 54.47, 0.58)

[Info   : Unity Log] 04/12/2024 14:00:42: Minimap: Adding unique location (3006.99, 34.41, 3837.71)

[Error  : Unity Log] MissingFieldException: Field not found: UnityEngine.Vector3 .ZoneLocation.m_generatorPosition Due to: Could not find field in class
Stack trace:
VentureValheim.LocationReset.LocationReset.TryReset (LocationProxy loc, System.Int32 hash, System.Boolean force) (at <21310b1290364205b032ca79a17a7369>:0)
VentureValheim.LocationReset.LocationProxyReset+<WaitForReset>d__3.MoveNext () (at <21310b1290364205b032ca79a17a7369>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <ab14d35a27c043688812ae199c64b5aa>:0)

[Error  : Unity Log] MissingFieldException: Field not found: UnityEngine.Vector3 .ZoneLocation.m_generatorPosition Due to: Could not find field in class
Stack trace:
VentureValheim.LocationReset.LocationReset.TryReset (LocationProxy loc, System.Int32 hash, System.Boolean force) (at <21310b1290364205b032ca79a17a7369>:0)
VentureValheim.LocationReset.LocationProxyReset+<WaitForReset>d__3.MoveNext () (at <21310b1290364205b032ca79a17a7369>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <ab14d35a27c043688812ae199c64b5aa>:0)

[Info   : Unity Log] 04/12/2024 14:00:44: Starting music home

**Comment by OrianaVenture** [comment]
If you are playing on game version 217.46 please make sure you are using version 0.8.2 of Location Reset.
