### ISSUE TITLE
Terrain Reset Thingy

### ISSUE THREAD

**Issue by General-Ripper** [OrianaVenture/VentureValheim#38]
Question!
Is it supposed to reset the Instances created by terrain modification? cuz it's not doing that thing.
Thanks.

**Comment by OrianaVenture** [comment]
Hi there, what mod are you referring to? I have two mods that can reset the terrain. I will need you to be more specific about your problem and show screenshots and provide a log file if possible. You can always contact me on my discord for faster support too.
