### ISSUE TITLE
NoDamageFlash config for Blood Magic only?

### ISSUE THREAD

**Issue by Oosquai** [OrianaVenture/VentureValheim#45]
Hi Venture!  Thanks for NoDamageFlash - very nice QoL mod.  Could I please ask if you'd be willing to add a config (or just a variation of the mod if that's easier than adding a config) allowing us to only remove the flash when it's self-inflicted by Blood Magic weapons? 
 Thanks!

**Comment by Oosquai** [comment]
Thank you!  That would be awesome!

**Comment by OrianaVenture** [comment]
This is now possible in version 0.2.0

**Comment by Oosquai** [comment]
It works beautifully!  Thank you so much!
