### ISSUE TITLE
LockEquipment - FaderDrop?

### ISSUE THREAD

**Issue by Oosquai** [OrianaVenture/VentureValheim#46]
Hi again!  I'm adding custom content to Deep North on my server.  Is there any way you could please provide a way within World Advancement Progression to check for the defeated_fader key when LockEquipment is turned on?  Example, would you consider making recipes including FaderDrop check for defeated_fader?  Thanks!

**Comment by OrianaVenture** [comment]
The mod should already check for that, is it not working properly?

**Comment by Oosquai** [comment]
Oh geez, my bad.  I'll check tonight.  Sorry to bother you.  I was reading the Thunderstore page and didn't see it.  I assumed, which we all know is bad!  Thanks, I'll report back!

**Comment by Oosquai** [comment]
It's working great!  Thanks, and sorry for the interruption!  Thanks for all your awesome mods!  :)

**Comment by OrianaVenture** [comment]
No worries, glad you like them!
