### ISSUE TITLE
Bonemaw Serpent Bug

### ISSUE THREAD

**Issue by Albarcelos** [OrianaVenture/VentureValheim#47]
When get near a Bonemaw Serpent the game get buged and the player fall under the world, the boat sink to the bottom of the ocean and player get stuck on an endless fall even after using teleport on console and teleport mod.

**Comment by OrianaVenture** [comment]
Is this with the latest floating items update 0.3.0? And did you enable making all items float?

**Comment by Albarcelos** [comment]
Hi, yes and yes, i also removed the nails to from the sink list

**Comment by OrianaVenture** [comment]
I have successfully recreated the bug with the original floating items mod. If you want to fix it temporarily disable that config, I will investigate what is causing it and get a fix as soon as I'm able.

**Comment by Albarcelos** [comment]
Ok, thank you very much

**Comment by OrianaVenture** [comment]
Sorry for the delay, this is fixed in Version 0.3.1
